# Generated by Django 5.2.8 on 2025-11-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номи категория')),
                ('description', models.TextField(blank=True, verbose_name='Тавсифи')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорияҳо',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳа')),
                ('description', models.TextField(verbose_name='Тавсифи мушкилот')),
                ('address', models.CharField(max_length=300, verbose_name='Суроға')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Арз')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Тӯл')),
                ('status', models.CharField(choices=[('reported', 'Мушкилот дар интиқор'), ('in_progress', 'Дар ҳоли иҷро'), ('resolved', 'Ҳал шуд'), ('closed', 'Пӯшида шуд')], default='reported', max_length=20, verbose_name='Ҳолат')),
                ('priority', models.CharField(choices=[('low', 'Паст'), ('medium', 'Миёна'), ('high', 'Баланд'), ('critical', 'Ҳаётан муҳим')], default='medium', max_length=20, verbose_name='Аҳамият')),
                ('votes', models.IntegerField(default=0, verbose_name='Миқдори овозҳо')),
                ('views', models.IntegerField(default=0, verbose_name='Миқдори дидан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи эҷод')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Санаи навсозӣ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Санаи ҳал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.category', verbose_name='Категория')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Мушкилкунанда')),
            ],
            options={
                'verbose_name': 'Мушкилот',
                'verbose_name_plural': 'Мушкилотҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Матни шарҳ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи фиристодан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Санаи навсозӣ')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Ҳалли пешниҳодӣ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue', verbose_name='Мушкилот')),
            ],
            options={
                'verbose_name': 'Шарҳ',
                'verbose_name_plural': 'Шарҳҳо',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issues/%Y/%m/%d/', verbose_name='Акс')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Шарҳ')),
                ('is_before', models.BooleanField(default=True, verbose_name='Акси пеш аз ҳал?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issues.issue')),
            ],
            options={
                'verbose_name': 'Акси мушкилот',
                'verbose_name_plural': 'Аксҳои мушкилот',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳа')),
                ('message', models.TextField(verbose_name='Паём')),
                ('is_read', models.BooleanField(default=False, verbose_name='Хонда шуд?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана эҷод')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.issue', verbose_name='Мушкилот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Огоҳинома',
                'verbose_name_plural': 'Огоҳиномаҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳа')),
                ('description', models.TextField(verbose_name='Тавсиф')),
                ('order', models.IntegerField(default=0, verbose_name='Тартиб')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол аст?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Қоида',
                'verbose_name_plural': 'Қоидаҳо',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Холҳо')),
                ('level', models.IntegerField(default=1, verbose_name='Сатҳ')),
                ('bio', models.TextField(blank=True, verbose_name='Дар бораи ман')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Рақами телефон')),
                ('issues_reported', models.IntegerField(default=0, verbose_name='Миқдори мушкилотҳои эҷодшуда')),
                ('issues_resolved', models.IntegerField(default=0, verbose_name='Миқдори мушкилотҳои ҳалшуда')),
                ('comments_written', models.IntegerField(default=0, verbose_name='Миқдори шарҳҳо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профили корбар',
                'verbose_name_plural': 'Профилҳои корбарон',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи овоздиҳӣ')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue', verbose_name='Мушкилот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Овоз',
                'verbose_name_plural': 'Овозҳо',
                'unique_together': {('user', 'issue')},
            },
        ),
    ]
